name: "Test: Kubernetes version"

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  k8s-version:
    runs-on: ubuntu-latest
    steps:
      - uses: loft-sh/setup-vind@main
        with:
          kubernetes-version: "1.31.0"
      - name: Verify kubernetes version
        run: |
          kubectl version -o json | jq '.serverVersion.gitVersion'
          kubectl get nodes -o wide
